name: Georgia
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
collections: 
    projects:
        output: true
        permalink: /:collection/:name
    work_research:
        output: true
        permalink: /:collection/:name
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
include:
    - _pages